### ISSUE TITLE
[Bug] Docs arrows for dropdown UI malfunctioning

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/svelte-cloudinary#101]
# **Bug Report**

## **Describe the bug**

Something funky going on with the dropdown arrows and generally the UI here

<img width="467" alt="image" src="https://github.com/cloudinary-community/svelte-cloudinary/assets/1045274/1214b58e-19cf-4cd4-af2b-dba1ce4581c1">

**Comment by ghostdevv** [comment]
Will be released in #112
