### ISSUE TITLE
[Feature] Homepage Updates

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/svelte-cloudinary#103]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

I updated the Next Cloudinary homepage recently. We can either pull the same layout and all, geared towards Svelte, or come up wit ha new design based potentially on if there are existing ecosystem patterns that are common?

https://next.cloudinary.dev/

Not strong preferences but would like to see an update. Happy to help provide a design for it if we don't just go with the same layout. The content is primarily written in Tailwind

https://github.com/cloudinary-community/next-cloudinary/blob/main/docs/pages/index.mdx

**Comment by ghostdevv** [comment]
Will be released in #112
