### ISSUE TITLE
[Bug] Remove `VITE_` for SvelteKit .env variable

### ISSUE THREAD

**Issue by mislam** [cloudinary-community/svelte-cloudinary#105]
# **Bug Report**

## **Describe the bug**

After upgrading from v1.2.3 to v1.3.1, I noticed the .env variable changed:
from `PUBLIC_CLOUDINARY_CLOUD_NAME` to -> `VITE_PUBLIC_CLOUDINARY_CLOUD_NAME`

The use of `VITE_` is counter-intuitive for SvelteKit project. It makes more sense to do one of the 3 options:

Option 1: Revert back to `PUBLIC_CLOUDINARY_CLOUD_NAME`, or
Option 2: Let the developer decide on naming and have a config/init to manually initialize the component using the custom env variable name.
Option 3. Let both naming (with and w/o `VITE_`) work, if some people prefer to must have `VITE_`.

## **Is this a regression?**

Did this behaviour used to work in the previous version?
Yes, the previous version in which this bug was not present was: v1.2.3

## **Steps To Reproduce the error**

1. Create a SvelteKit project
2. npm install svelte-cloudinary v1.2.3
3. Use .env variable `PUBLIC_CLOUDINARY_CLOUD_NAME`
4. Then upgrade the package to v1.3.1

## **Expected behaviour**

Like all other SvelteKit .env variable naming convention, the `VITE_` prefix should be removed.

### **Your environment**

- OS: macOS v12.7.4
- Node version: v20.10.0
- pnpm version: v8.15.5
- Browser name and version: Brave v1.64.113

**Comment by colbyfayock** [comment]
hey @mislam - 1.2.1 attempted to introduce a new ENV configuration that would allow for both patterns of VITE_ and PUBLIC_ to work: https://github.com/cloudinary-community/svelte-cloudinary/pull/82

however, the issue with this, is it inadvertently broke vanilla Svelte installations, and while SvelteKit likely makes up the majority of use, it was a breaking change that shouldn't have been released as a minor update (if at all), hence the decision to revert it: https://github.com/cloudinary-community/svelte-cloudinary/pull/97

we're trying to figure out a solution that would allow for use of different ENV naming patterns to let any Svelte project utilize this library, whether VITE_, PUBLIC_, or another less frequent pattern, but need to figure out a good way to handle that

thanks for sharing some ideas on how to move forward with that idea, i'll let the maintainer chime in when she has time about what she had in mind as well

**Comment by enesbala5** [comment]
Facing this issue also. For now I'm having to define it twice,  which is unnecessarily verbose. Hoping this is solved soon.

**Comment by ghostdevv** [comment]
> Facing this issue also. For now I'm having to define it twice, which is unnecessarily verbose. Hoping this is solved soon.

Could you share why you need to define it twice? What are you running into where you're using both?

**Comment by ghostdevv** [comment]
Will be released in https://github.com/cloudinary-community/svelte-cloudinary/pull/112 - we've switched to the following naming scheme as it's the most compatible between different setups:

- `PUBLIC_CLOUDINARY_CLOUD_NAME`
- `PUBLIC_CLOUDINARY_API_KEY`
- `PUBLIC_CLOUDINARY_PRIVATE_CDN`
- `PUBLIC_CLOUDINARY_SECURE_DISTRIBUTION`
- `PUBLIC_CLOUDINARY_UPLOAD_PRESET`

**Comment by ghostdevv** [comment]
nvm my testing wasn't quite accurate so reopening this

**Comment by ghostdevv** [comment]
I wasn't able to get this working as I originally hoped, so we'll have to keep the `VITE_` prefix for now. We can't only use SvelteKit `$env` since we want this library to work with vanilla Svelte. I'm open to exploring supporting `import.meta.env.PUBLIC_...` in the future, by users expanding their [`envPrefix`](https://vitejs.dev/config/shared-options.html#envprefix) in their vite config

You can always use the new `configureCloudinary` function that will be released in v2 if you want to use SvelteKit's env system, but we can't do this automatically for you atm

I'll close this for now and we can revisit this in the future if it's a real pain point :pray:
