### ISSUE TITLE
[Feature] Add config support to CldVideoPlayer, CldUploadWidget. Add global environment variables for CNAME

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/svelte-cloudinary#107]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

* Config prop for CldUploadWidget
* Config prop for CldVideoPlayer
* Add support for global environment variables for secureDistribution and privateCdn

## **Describe the solution you'd like**
 
Like the CldImage prop, the CldUploadWidget and CldVideoPlayer should accept a config prop allowing for individual instance configuration.

The Upload Widget would allow configuration of Cloud Name and API key where the Video Player would allow Cloud Name, Secure Distribution, and Private CDN

They can all be typed as ConfigOptions which comes from the URL Loader package (similar to CldImage)

To allow configuring these at a global scale, we can add 2 environment variables, also allowing these to be enviornment dependent:

```
PUBLICPREFIX_CLOUDINARY_SECURE_DISTRIBUTION="spacejelly.dev"
PUBLICPREFIX_CLOUDINARY_PRIVATE_CDN=true
```

Here are the relevant code changes in the Next.js repo: https://github.com/cloudinary-community/next-cloudinary/pull/466

**Comment by ghostdevv** [comment]
> Like the CldImage prop, the CldUploadWidget and CldVideoPlayer should accept a config prop allowing for individual instance configuration.

This is done in #112

> Add support for global environment variables for secureDistribution and privateCdn

Not done yet

**Comment by ghostdevv** [comment]
Will be released in https://github.com/cloudinary-community/svelte-cloudinary/pull/112
