### ISSUE TITLE
[v2] confirm analytics is working 

### ISSUE THREAD

**Issue by ghostdevv** [cloudinary-community/svelte-cloudinary#128]
https://github.com/cloudinary-community/svelte-cloudinary/pull/112#discussion_r1747676114

> it doesnt look like the analytics is working properly, this is from the docs
> ![image](https://github.com/user-attachments/assets/2dc6a393-2de0-4a55-aa60-61ddabb6e6ee)

**Comment by ghostdevv** [comment]
@colbyfayock what should that URL look like, and can you see anything wrong here: https://github.com/cloudinary-community/svelte-cloudinary/blob/15aaa2aef11def8a2396338432b0debcada02ff9/packages/svelte-cloudinary/src/config.ts#L12

**Comment by colbyfayock** [comment]
example from the Astro homepage: 

```
https://res.cloudinary.com/astro-cloudinary/image/upload/c_fill,w_1600,h_1200,g_center/l_assets:pill-bad-red_ceyitm,w_400/fl_layer_apply,fl_no_overflow,g_south_east,y_180/l_text:Source%20Sans%20Pro_74_black:3%252E2%20mb,co_white/fl_layer_apply,fl_no_overflow,g_south_west,y_214,x_1340/l_assets:pill-good-green_aaoi4h,w_400/fl_layer_apply,fl_no_overflow,g_south_east,y_50/l_text:Source%20Sans%20Pro_74_black:134%20kb,co_white/fl_layer_apply,fl_no_overflow,g_south_west,y_82,x_1340/c_limit,w_1600/f_auto/q_auto/v1/samples/landscapes/nature-mountains?_a=BBGOphXg0

?_a=BBGOphXg0
```

**Comment by ghostdevv** [comment]
ah it was the `-` in the version numbers! thankfully you had this  function in astro-cloudinary or it might've taken forever to debug

https://github.com/cloudinary-community/astro-cloudinary/blob/b304e0836221773f86311a4b7cecdbd4a9e66db9/astro-cloudinary/src/constants/analytics.ts#L9
