### ISSUE TITLE
[v2] check behaviour of onSuccess

### ISSUE THREAD

**Issue by ghostdevv** [cloudinary-community/svelte-cloudinary#134]
Migration notes on this might need re-wording, and behaviour might be slightly wrong?

**Comment by ghostdevv** [comment]
> so actually there may not be a difference in Svelte after looking at the code,  maybe you can confirm this. in React i was storing the results in state and then using that as the basis of triggering onUpload, as opposed to onSuccess that was just being triggered directly in the callback, so functionally it was a bit different

Could you clarify what this means? @colbyfayock like the difference in the results type here?

**Comment by colbyfayock** [comment]
not the type, the mechanics in how the callback is triggered

**Comment by ghostdevv** [comment]
> not the type, the mechanics in how the callback is triggered

I'm just not sure that I understand what the difference is. You say you're storing the results in state and then using that to trigger onUpload, but when are these results set? Is it not on the success event?

> like the difference in the results type here?

I phrased this bad - what I meant is that, is there a difference between the `results` object passed to `onSuccess` and passed to `onUpload`?

**Comment by colbyfayock** [comment]
the point may be moot in svelte, im not sure what the code looks like, but in react, triggering 10 state updates within a second where a callback depends on the state change would yield different results than 10 direct callbacks being triggered, they mechanically work different. this is to make sure svelte isnt doing something similar. the point was to explain what the difference was and there may not be a difference in svelte if thats not the case

**Comment by ghostdevv** [comment]
Ah [looking at the code](https://github.com/cloudinary-community/next-cloudinary/blob/80c33a970bb3bad6c5b53ac87b33685a6b88eb2c/next-cloudinary/src/components/CldUploadWidget/CldUploadWidget.tsx#L100) again I think I mostly understand. I think the behaviour we have here is fine, and is also inline with how v1 functioned. If anyone has any issues, please tag me and I'll re-open!
