### ISSUE TITLE
Hacktoberfest 2024

### ISSUE THREAD

**Issue by ghostdevv** [cloudinary-community/svelte-cloudinary#142]
Welcome to Hacktoberfest 2024! Cloudinary is participating in Hacktoberfest by giving away 50 swag kits away to eligible contributions, find out more [here](https://cloudinary.com/blog/hacktoberfest-open-source-celebration-cloudinary).

Any issue labelled "[hacktoberfest](https://github.com/cloudinary-community/svelte-cloudinary/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+label%3Ahacktoberfest)" is up for grabs, please just let me know in the issue that you want to work on it.

You can read our [contributing guide](https://github.com/cloudinary-community/svelte-cloudinary/blob/main/CONTRIBUTING.md), which contains information on how to get setup and work on issues. If you need any help, please reach out on here or in the issue and I'm more than happy to guide you.

Hacktoberfest is a wonderful opportunity to get into open source contributions, or level up your existing ones. Checkout the [other projects that are participating](https://github.com/topics/hacktoberfest) too!

Issues might get added randomly during the month, so check back occasionally to see if there's anything new.

**Comment by ovindu-a** [comment]
Hi @ghostdevv, I was browsing through the cloudinary repos, however, I didn't find any labelled issues. Please let me know if there's any issues I can help with

**Comment by ghostdevv** [comment]
@ovindu-a hey! I've just added a couple issues, I'll keep working on adding some more as we go through the month :pray:

**Comment by ghostdevv** [comment]
We're currently in the process of releasing v2. I'm waiting for some settings to be changed on the repo, then it'll be done. It might be worth waiting till this time tomorrow, or until I let you folks know, before contributing - as some links I add in the issues might be broken until then :pray:

**Comment by ovindu-a** [comment]
Thank you @ghostdevv! I will have a look

**Comment by ovindu-a** [comment]
Will do @ghostdevv

**Comment by ghostdevv** [comment]
Thanks to everyone that participated in Hacktoberfest this year! I hope you enjoy the swag :sunglasses: I'll close this for now, but feel free to comment on issues if you still want to contribute. I'll add the [good first issue](https://github.com/cloudinary-community/svelte-cloudinary/issues?q=sort%3Aupdated-desc+is%3Aopen+label%3A%22good+first+issue%22) tag to them.
