### ISSUE TITLE
Add a custom domain guide

### ISSUE THREAD

**Issue by ghostdevv** [cloudinary-community/svelte-cloudinary#143]
We're using [Starlight](https://starlight.astro.build/) for docs currently, so you can create the guide at `packages/docs/src/content/guides/custom-domain.mdx`. The guide should show how you can [configure](https://svelte-cloudinary-owp4prvso-cloudinarydevx.vercel.app/config) svelte-cloudinary with the `private cdn` option to be true, and the `secure distribution` option to be your custom domain. It should link to the [official cloudinary docs](https://cloudinary.com/documentation/advanced_url_delivery_options#private_cdns_and_custom_delivery_hostnames_cnames) and [include a note](https://starlight.astro.build/guides/authoring-content/#asides) that it's only available on the advanced plan.

**Comment by error9098x** [comment]
I would love to take this task. Could you assign it to me.
