### ISSUE TITLE
add jsdoc descriptions to the helpers

### ISSUE THREAD

**Issue by ghostdevv** [cloudinary-community/svelte-cloudinary#144]
The [getCldImageUrl](https://github.com/cloudinary-community/svelte-cloudinary/blob/3229a9ef40ea93e2f55535710eca53449e73fdf8/packages/svelte-cloudinary/src/helpers/getCldImageUrl.ts#L9) and [getCldOgImageUrl](https://github.com/cloudinary-community/svelte-cloudinary/blob/3229a9ef40ea93e2f55535710eca53449e73fdf8/packages/svelte-cloudinary/src/helpers/getCldOgImageUrl.ts#L8) helpers should have jsdoc comments that include: a short description of what they are, an example of how to use it, and a link to the docs page.

Example: https://github.com/cloudinary-community/svelte-cloudinary/blob/c0031086ab988167e9c5fc80fe1d94356e7765e7/packages/svelte-cloudinary/src/config.ts#L97-L113

**Comment by ovindu-a** [comment]
Hi @ghostdevv, can I start with this? Seems like a good issue to do first.

**Comment by ghostdevv** [comment]
go for it! @ovindu-a

**Comment by ovindu-a** [comment]
@ghostdevv I have made a pull request. Please let me know if there is anything that I've missed as this is my first time here.
