### ISSUE TITLE
add tests for CldOgImage

### ISSUE THREAD

**Issue by ghostdevv** [cloudinary-community/svelte-cloudinary#145]
We use [vitest](https://vitest.dev/) for our testing suite, and the tests are located in [packages/svelte-cloudinary/tests](./packages/svelte-cloudinary/tests). We just need some simple tests that cover basic functionality for now, similar to the example below:

Example: https://github.com/cloudinary-community/svelte-cloudinary/blob/main/packages/svelte-cloudinary/tests/CldImage/CldImage.test.ts

**Comment by ovindu-a** [comment]
@ghostdevv, I can work on these tests. Can you assign this to me?
