### ISSUE TITLE
add tests for getCldImageUrl

### ISSUE THREAD

**Issue by ghostdevv** [cloudinary-community/svelte-cloudinary#146]
We use [vitest](https://vitest.dev/) for our testing suite, and the tests are located in [packages/svelte-cloudinary/tests](./packages/svelte-cloudinary/tests). We just need some simple tests that cover basic functionality for now

**Comment by ovindu-a** [comment]
I will create these tests too @ghostdevv

**Comment by moonlander101** [comment]
I can work on this

**Comment by ghostdevv** [comment]
Oops I've only just seen this - Let's let @ovindu-a take this if he is still interested, as he asked first. I'll try and create some more hacktoberfest issues tomorrow @moonlander101

**Comment by ovindu-a** [comment]
@ghostdevv since this is a good first issue, I don't mind letting @moonlander101 work on this. I'll work on any other issues that come up if that's okay with you.

**Comment by moonlander101** [comment]
> Oops I've only just seen this - Let's let @ovindu-a take this if he is still interested, as he asked first. I'll try and create some more hacktoberfest issues tomorrow @moonlander101

Ok thanks

**Comment by ghostdevv** [comment]
Hey @moonlander101, did you get a chance to look at this?

**Comment by moonlander101** [comment]
> Hey @moonlander101, did you get a chance to look at this?

Hi yes, I'll work on a few test cases.

**Comment by moonlander101** [comment]
@ghostdevv , Are [these](https://github.com/cloudinary-community/svelte-cloudinary/pull/162) tests ok?

**Comment by ghostdevv** [comment]
Hey @moonlander101, I'm so sorry I have only just been able to get to this :pray:
