### ISSUE TITLE
[Feature] Config prop for CldImage

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/svelte-cloudinary#25]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

Add the option of passing in the config prop to the component at an individual level to allow for per-component config like cloud name

## **Describe the solution you'd like**

See example: https://github.com/colbyfayock/next-cloudinary/blob/main/next-cloudinary/src/components/CldImage/CldImage.tsx#L109C92-L109C101

## **Additional context**

A way to test this is have 2 component that each reference a different Cloud name

**Comment by colbyfayock** [comment]
i tagged the wrong issue, this wasn't released

**Comment by matiasfha** [comment]
Released/Solved
