### ISSUE TITLE
[Bug] Type errors on width/height

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/svelte-cloudinary#27]
# **Bug Report**

## **Describe the bug**

When testing the latest, i seem to be getting type errors for width and height

<img width="802" alt="image" src="https://github.com/cloudinary-community/svelte-cloudinary/assets/1045274/50b8e06d-ea1d-4ce5-bc1f-6fa92aa40fd2">

**Comment by colbyfayock** [comment]
@matiasfha not quite sure why this is happening

**Comment by matiasfha** [comment]
It uses width and height as numbers.
`width={600}` 

Should we support them as strings too?

but, what other props are you passing there?

**Comment by colbyfayock** [comment]
i have it set to allow string and numbers because people stylistically have different preferences on how to pass that in

https://github.com/colbyfayock/cloudinary-util/blob/main/packages/url-loader/src/types/asset.ts#L28

i feel like its more common to see it passed in as a string

**Comment by colbyfayock** [comment]
example with the other props:
```
<CldImage
	width="600"
	height="600"
	src="images/turtle"
	alt="turtle"
	overlays={[{
		publicId: `images/earth`,
		position: {
			x: 10,
			y: 10,
			gravity: 'north_west',
		},
		effects: [
			{
				crop: 'fill',
				gravity: 'auto',
				width: 200,
				height: 200
			}
		]
	}]}
/>
```

**Comment by matiasfha** [comment]
Been working on refactor the type for the props to respect
`width: number | string | undefined`
`height: number | string | undefined`
and also the rules related with `layout` inherited from `unpic`
- `layout='fullWidth'  => width should not be present
- other layout values width and height should be present

but for some reason TS "swallow" the types and expose width and height as strings | undefined removing  the `number` type

When merging `ImageOptions` (from cloudinary-util library) and `ImageProps` (from unpic) those types are wrongly merged. If you Omit width and height from both ends to define them in here the layout rules are missed.
If I rewrite the layout rules by omitting `height` , `width` and `layout` from `ImageOptions` and `ImageProps` 
I get another weird ts Error saying that `fullWidth` is not a valid option.
I'll keep working on it tho

**Comment by colbyfayock** [comment]
@matiasfha you said this is resolved right? So it can be closed?

**Comment by matiasfha** [comment]
Release/Solved
