### ISSUE TITLE
[Bug] Multiple renders prevent config object from working

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/svelte-cloudinary#34]
# **Bug Report**

## **Describe the bug**

When passing in a config object, the CldImage component appears to make multiple passes ignoring the `config` property on the hydrated pass in the browser.

See comment from the PR that added the capability here: https://github.com/cloudinary-community/svelte-cloudinary/pull/30#issuecomment-1604687883

**Comment by colbyfayock** [comment]
did we ever figure this out @matiasfha ?

**Comment by matiasfha** [comment]
This seems to be working now
