### ISSUE TITLE
[Bug] Documentation is using Next Cloudinary images with open graph template

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/svelte-cloudinary#35]
# **Bug Report**

## **Describe the bug**

I'll need to upload the appropriate template image to use for Svelte

**Comment by colbyfayock** [comment]
<img width="1271" alt="image" src="https://github.com/cloudinary-community/svelte-cloudinary/assets/1045274/60600786-26b6-44fc-b343-ad472a063974">

**Comment by matiasfha** [comment]
Fixed!
<img width="551" alt="CleanShot 2023-06-30 at 11 21 41@2x" src="https://github.com/cloudinary-community/svelte-cloudinary/assets/282006/b7465e6d-b2d2-4b76-ba42-db4171a4cca5">
