### ISSUE TITLE
[Feature] Can the src and alt props be reactive?

### ISSUE THREAD

**Issue by troyciesco** [cloudinary-community/svelte-cloudinary#40]
# **Feature Request**
I'm currently trying to build a modal that contains a `CldImage` component, and that image updates based on the image the user selected on the main gallery page. In doing so, I noticed that the image displayed by `CldImage` does not update when props change.

I'm wondering if this was intentional or if some of the values in `CldImage.svelte` should be reactive instead of using `const`. 

## **Is your feature request related to a problem? Please describe.**

A minimal reproduction looks something like this in `svelte-cloudinary/src/routes/+page.svelte`:
1. when i click one of the three buttons, i expect both the "cloudinary image" and the "regular image" to update to what i've selected
2. "regular image" will update when i click a button, but "cloudinary image" will not

Note: I used the supplied sample images, and you'll want to replace CLOUDNAME in the img src if you want to replicate

```
<script>
	import CldImage from '$lib/components/CldImage.svelte';
	const images = [
		{ fileName: 'woman-headphones' },
		{ fileName: 'turtle' },
		{ fileName: 'sneakers' }
	];
	let mainImage = 'earth';

	const handleSelectImage = (imgIndex) => {
		mainImage = images[imgIndex].fileName;
	};
</script>

<div>
	<h1>Cloudinary Image</h1>
	<CldImage
		layout="fullWidth"
		height="180"
		objectFit="contain"
		src={`images/${mainImage}`}
		alt={mainImage}
		quality="80"
	/>
</div>
<div>
	<h1>Regular Image</h1>
	<h2>{mainImage}</h2>
	<img
		height={180}
		width="auto"
		src={`https://res.cloudinary.com/<CLOUDNAME>/image/upload/f_auto/q_80/v1/images/${mainImage}`}
		alt=""
	/>
</div>
<div>
	<h2>buttons</h2>
	{#each images as image, i}
		<button on:click={() => handleSelectImage(i)}>
			<CldImage
				class="cursor-pointer"
				layout="fullWidth"
				height={150}
				objectFit="cover"
				src={`images/${image.fileName}`}
				alt={image.fileName}
				quality="80"
			/>
		</button>
	{/each}
</div>
```

Here I'd just clicked sneakers:
<img width="948" alt="Screenshot 2023-07-08 at 5 41 27 PM" src="https://github.com/cloudinary-community/svelte-cloudinary/assets/24758859/44dc2947-b461-4fb5-888a-e94354524168">

## **Describe the solution you'd like**

imho, I think one should be able to dynamically update `src` and `alt` at the very least (but again, maybe there was a reason not to).

To at least prove this could work, I changed the deconstruction on L18 to be reactive:
```diff
- 	{ alt, src, width, height, config } = $$props as $$Props;
+ 	$: ({ alt, src, width, height, config } = $$props as $$Props);
```

Then I added the reactive `src` value instead of using the static `imageProps` one (more on `imageProps` in a second) to the transformer prop:
```diff
<Image
	{...imageProps}
	cdn="cloudinary"
	transformer={({ width }) => {
		const options = {
			...imageProps,
			...cldOptions,
+			src,
			// Without, get a "never" type error on options.width
			width: imageProps.width
		};
       ....
``` 

I did start to try to update imageProps defined on L30 since that's currently static, but I was getting an error of `TypeError: Cannot set properties of undefined (setting 'layout')` when I did, so instead of tinkering with it I figured I'd find out if making these changes even makes sense first.

## **Describe alternatives you've considered**

Since my particular use case is a modal, I'd imagine I can probably use lifecycle methods or similar to destroy/recreate the `CldImage` on open/close. but I'd also like to have it be a slideshow with clickable thumbnails at the bottom, so it seems like things might get tricky there.

Also, since this is just for pictures of cool wildlife I've seen and basically only like 8 people are going to use this site, I might just use an `img` or even the underlying unpic `Image` instead. But I _think_ to use `svelte-cloudinary` on a bigger app I'd want to know that this would work, or at least understand why I should do it a different way.

## **Additional context**

I'm open to helping with this if needed!

**Comment by colbyfayock** [comment]
@matiasfha any thoughts on this one?

**Comment by matiasfha** [comment]
The request makes total sense I’ll take a look asap.
Also thanks for the research and the tests made.
You’re right we can enable reactivity on props
