### ISSUE TITLE
[Feature]  Allow to pass an url as src to CldVideoPlayer

### ISSUE THREAD

**Issue by matiasfha** [cloudinary-community/svelte-cloudinary#57]
# **Feature Request**

Sets up the CldVideoPlayer to allow passing in a valid Cloudinary URL as a src

Example:

`src="https://res.cloudinary.com/next-cloudinary/video/upload/v1/videos/mountain-stars.webm"`

Similar to CldImage, the URL must include a version number /v1234/

**Comment by colbyfayock** [comment]
SEe how we're doing it in Next Cloudinary with the Cloudinary Util function: https://github.com/colbyfayock/next-cloudinary/blob/main/next-cloudinary/src/components/CldVideoPlayer/CldVideoPlayer.tsx#L47

**Comment by matiasfha** [comment]
This is already implemented
