### ISSUE TITLE
[Feature]  Throw an error or warning in components if a cloud name is not set

### ISSUE THREAD

**Issue by matiasfha** [cloudinary-community/svelte-cloudinary#58]
# Feature Request

## Is your feature request related to a problem? Please describe.

A Cloud name is required, whether set via VITE_PUBLIC_CLOUDINARY_CLOUD_NAME or via the config prop. The component should throw an error or warning in the event that it's not configured.

**Comment by HeetVekariya** [comment]
@matiasfha I can work on this issue

**Comment by matiasfha** [comment]
Hi @HeetVekariya Thanks for taking care of this issue.
Go ahead and work on it, let me know if you need any help or clarification

**Comment by colbyfayock** [comment]
@HeetVekariya i have this same Issue filed in Next Cloudinary and one suggestion the person who wanted to work on it provided was to create a helper function to perform this check and add it to the various locations as ultimately this is something all of the components need:

https://github.com/colbyfayock/next-cloudinary/issues/264#issuecomment-1749912285

perhaps there's a similar solution

you both can feel free to discuss this in my discord server if you'd like: https://spacejelly.dev/discord

Cloudinary has a discord server but there's not really a place that makes sense for that kind of discussion at this time, but linking in case generally interested: https://discord.gg/cloudinary
