### ISSUE TITLE
[Feature]  Picture Tag Component

### ISSUE THREAD

**Issue by matiasfha** [cloudinary-community/svelte-cloudinary#59]
# Feature Request

## Is your feature request related to a problem? Please describe.

The library currently supports CldImage giving developers a simple way to use cloudinary assets.

An alternative image-related element is the [picture](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture) element which allows for different capabilities.

Having this would allow developers to use Cloudinary in a way that makes more sense for Picture-related usage.

## Describe the solution you'd like
A basic usage pulled from MDN is:

```html
<picture>
    <source
        srcset="/media/cc0-images/surfer-240-200.jpg"
        media="(min-width: 800px)">
    <img src="/media/cc0-images/painted-hand-298-332.jpg" alt="">
</picture>
```

Theoretically, it would make sense that the <img above would be the <CldImg, where <picture becomes a wrapper with an additional <source element, leaving something along hte lines of:

```jsx
<CldPicture>
    <CldSource
        srcset={[{ src: 'cc0-images/surfer', width: 240, height: 200 }]}
        media="(min-width: 800px)"
    />
    <CldImg width="298" height="332" src="cc0-images/painted-hand" alt="" />
</CldPicture>
```

This is just an idea and am open to ideas and suggestions.

**Comment by colbyfayock** [comment]
a few things to think about, Matt Kane just recently tweeted about Unpic support:

https://twitter.com/ascorbic/status/1707494849543327828

Additionally, the way Next Image works is using the native tags:

https://nextjs.org/blog/next-13-5#nextimage-improvements

as much as i find it weird using the native <picture> tag to wrap the custom components, wondering what CldPicture would actually do under the hood?

**Comment by colbyfayock** [comment]
Closing this for now
