### ISSUE TITLE
How to debug 400 bad request?

### ISSUE THREAD

**Issue by igorlanko** [cloudinary-community/svelte-cloudinary#68]
Hello,

Just installed and signed up for the Cloudinary, trying to figure out how to get it going. My media files are stored on Supabase, so using supabase-cloud env variables I'm trying to start this up locally like so:

```html
<!-- Works -->
<img src={`https://res.cloudinary.com/${BUCKET_ID}/image/fetch/w_300,c_fill/${artifact.src}`} alt={artifact.caption} />

<! -- Throws 400 bad request -->
<CldImage
  layout="fullWidth"
  src={artifact.src}
  alt={artifact.caption}
  height="auto"
/>
```
However using the component specifically I'm getting bad request in the browser:
![CleanShot 2023-12-02 at 16 54 11](https://github.com/cloudinary-community/svelte-cloudinary/assets/31314207/34ec022d-e0ae-4ad6-bf5a-c77ae30b682f)

Not sure how could I further debug this? Dev terminal doesn't have any errors. These are the variables I have in both `.env` and `env.local`:
```
VITE_PUBLIC_CLOUDINARY_CLOUD_NAME=
VITE_PUBLIC_CLOUDINARY_API_KEY=
CLOUDINARY_API_SECRET=
```

This is probably something stupidly simple I just can't seem to figure it out! 

Initially I thought maybe you can't make requests on localhost, but just using `<img>` seems to work? Could you give me a clue? Thanks!

**Comment by colbyfayock** [comment]
hey @igorlanko a good way to debug errors like that is to look in the Network tab, and the headers of the request. specifically, x-cld-error

check out this video: https://www.youtube.com/watch?v=ERurOuYT_WA&list=PL8dVGjLA2oMpaTbvoKCaRNBMQzBUIv7N8&index=53

**Comment by igorlanko** [comment]
Thanks so much! This is very helpful. The header response was: `Invalid transformation component - https:`. Looks like that's because I'm passing a public url from Supabase storage, while the library expects me to already have that file in the Cloudinary storage?

Anyway, this is probably not related to the library itself.

**Comment by colbyfayock** [comment]
@igorlanko yeah thats the default behavior to use the Cloudinary ID, however, we have a different delivery type called "fetch" which allows you to take a remote URL and pass it through

you can try this by setting `deliveryType="fetch"`

note: if you get errors, you may need to update your Security settings to allow Fetch (checkbox), where I'd also recommend restricting fetch requests to only your Supabase storage

**Comment by igorlanko** [comment]
@colbyfayock, it works!! Thanks so much!

Would you mind clarifying, when you're talking about restricting fetch requests to the Supabase storage, do you mean on the SvelteKit side in CSP or in Cloudinary settings?

**Comment by colbyfayock** [comment]
Cloudinary settings. That way someone can't pass in just any URL and it would work

<img width="922" alt="image" src="https://github.com/cloudinary-community/svelte-cloudinary/assets/1045274/4e4f7eac-8577-4d9a-b723-65e013bc724e">

**Comment by igorlanko** [comment]
Thank yo so very much again!
