### ISSUE TITLE
CldImage improvements

### ISSUE THREAD

**Issue by matiasfha** [cloudinary-community/svelte-cloudinary#83]
getCldImageUrl / CldImage
- [x] Avoid 2-step resizing to allow high resolution images from being generated in responsive breakpoints
Fixes: https://github.com/cloudinary-community/next-cloudinary/issues/327
- [x] Deprecate transformations in favor of new prop namedTransformations for clarity
- [x] Remove deprecated GetCldImageUrl

**Comment by ghostdevv** [comment]
Will be released in #112
