### ISSUE TITLE
[Bug] Revert ENV changes to avoid Svelte vs SvelteKit conflict

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/svelte-cloudinary#91]
# **Bug Report**

## **Describe the bug**

A change was made to try to provide support for both Svelte and SvelteKit ENV naming patterns:

https://github.com/cloudinary-community/svelte-cloudinary/pull/82
https://github.com/cloudinary-community/svelte-cloudinary/pull/90

But it sounds like this breaks traditional Svelte usage as the import of `$env/dynamic/public` for SvelteKit is not available and breaks.

Nearterm solution should be to revert these changes as a minor release and moving forward, come up with a more comprehensive solution for the next or a future major release

**Comment by MapleThunder** [comment]
Is there a work around to be able to build static sites as right now I can't. Is the only solution to revert to an earlier version of the package ?

**Comment by colbyfayock** [comment]
@MapleThunder working to get it addressed ASAP, but for now that would likely be the safest bet as I unfortunately don't have an exact timeline

can you share the issue that you're running into so we can make sure it's covered? is it simply that you're running a traditional Svelte site and it's not building?

**Comment by colbyfayock** [comment]
@MapleThunder nm my last message :) if you want to try 1.2.4, hopefully that addresses your issue
