### ISSUE TITLE
[Bug] Tests broken

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/svelte-cloudinary#92]
# **Bug Report**

## **Describe the bug**

<img width="902" alt="image" src="https://github.com/cloudinary-community/svelte-cloudinary/assets/1045274/54de165e-3833-4e7b-a9e8-b25623562355">

Tests are currently broken, though I suspect this is related to the ENV change: https://github.com/cloudinary-community/svelte-cloudinary/pull/82

Issue to resolve that problem: https://github.com/cloudinary-community/svelte-cloudinary/issues/91

**Comment by ghostdevv** [comment]
Tests appear to be broken in general, let's use this to track that
