### ISSUE TITLE
v2.0.0

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/svelte-cloudinary#93]
Features that should go into v2.0.0 that would expect to have breaking changes.

Working PR: https://github.com/cloudinary-community/svelte-cloudinary/pull/87

## getCldImageUrl / CldImage
- [x] Removes default 2-stage resizing to avoid low resolution images for larger source images
  * https://github.com/cloudinary-community/svelte-cloudinary/issues/83
  * Related: https://github.com/cloudinary-community/next-cloudinary/pull/431
- [x] Deprecate `transformations` in favor of new prop `namedTransformations` for clarity
  * https://github.com/cloudinary-community/svelte-cloudinary/issues/83
- [ ] Remove deprecated GetCldImageUrl
  * https://github.com/cloudinary-community/svelte-cloudinary/issues/83

## getCldOgImageUrl / CldOgImage
- [ ] Remove deprecated GetCldOgImageUrl
  * https://github.com/cloudinary-community/svelte-cloudinary/issues/84

## CldVideoPlayer
- [x] Remove `autoPlay` backwards compatibility
  * https://github.com/cloudinary-community/svelte-cloudinary/issues/85
- [x] Migrate Cloudinary types to native @cloudinary-util/types package

## CldUploadWidget
- [x] Update `onError` to follow `CldUploadEventCallback` pattern
- [x] Update `onClose` to follow `CldUploadEventCallback` pattern
- [x] Deprecate `onUpload` in favor of `onSuccess` and other targeted event handlers
- [x] Add Content-Type of `application/json` to CldUploadWidget fetch request: https://github.com/colbyfayock/next-cloudinary/issues/379
  * https://github.com/cloudinary-community/svelte-cloudinary/issues/86
  * Related: https://github.com/cloudinary-community/next-cloudinary/pull/418
- [x] Migrate Cloudinary types to native @cloudinary-util/types package

See similar and related changes made to Next Cloudinary: https://github.com/cloudinary-community/next-cloudinary/pull/407

**Comment by ghostdevv** [comment]
Tracking with milestone https://github.com/cloudinary-community/svelte-cloudinary/milestone/1
