### ISSUE TITLE
QOL / Structure Changes

### ISSUE THREAD

**Issue by ghostdevv** [cloudinary-community/svelte-cloudinary#98]
- [x] Include format lint, publint, and svelte-check in the test action
- [x] Enable autoformatting for vscode settings
- [x] Format the codebase and do a blame-ignore
- [x] Change structure

**Comment by ghostdevv** [comment]
I am starting to think that the repo structure would benefit from a change, perhaps something like:

```
packages/
	playground/
	svelte-cloudinary/
		tests/
		...
	docs/
```

What I want to achieve is a clear seperation between the SvelteKit app that is the playground and the actual package to avoid accidental breaking changes again. WDYT? @colbyfayock

**Comment by colbyfayock** [comment]
that makes sense to me! i found it a bit confusing that they were somewhat grouped but from one of our chats sounds like that was an older pattern and kinda just the way it was

so lets go for it
